version: '2'
volumes:
  ssh-agent:
    external: true
services:
  application:
    image: cweagans/bg-sync
    volumes:
      - .:/source
      - /var/www/application
    environment:
      - SYNC_DESTINATION=/var/www/application
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: noitacilppa
      MYSQL_USER: application
      MYSQL_PASSWORD: noitacilppa
      MYSQL_DATABASE: application
  nginx:
    image: nginx:1.9
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "80:80"
    volumes_from:
      - application:rw
    environment:
      NGINX_WEBROOT: "/var/www/application/Web"
      NGINX_PHP_HOST_AND_PORT: php:9000
      NGINX_SERVERNAME: application-dev
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: pcodk/php7
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes_from:
      - application:rw
    volumes:
      - ssh-agent:/ssh-agent
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PCO_ENV: dev
      FLOW_CONTEXT: Development/Docker
      SSH_AUTH_SOCK: /ssh-agent/ssh-agent.sock

#  devtools:
#    image: pcodk/devtools
#    volumes_from:
#      - application