#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

NEOS:
  Flow:
    persistence:
      backendOptions:
        host: 'mysql'
        dbname: 'application'       # adjust to your database name
        user: 'application'             # adjust to your database user
        password: 'noitacilppa'         # adjust to your database password
        driver: 'PDO'

       # if you want to log executed SQL queries, enable the next 2 lines
#      doctrine:
#        sqlLogger: 'TYPO3\Flow\Persistence\Doctrine\Logging\SqlLogger'
